# Generated By AI Start (Cursor)
"""
从 api_config.env 读取 OpenAI 兼容 API 配置，供后续调用直接使用。
"""
import os
from pathlib import Path


def _get_config_path():
    return Path(__file__).parent / "api_config_VAPI.env"


def _load_config():
    config = {}
    config_path = _get_config_path()
    if not config_path.exists():
        return config
    with open(config_path, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if line and "=" in line and not line.startswith("#"):
                key, _, value = line.partition("=")
                config[key.strip()] = value.strip()
    return config


_config_cache = None


def get_config():
    """读取并返回完整配置字典，结果会缓存。"""
    global _config_cache
    if _config_cache is None:
        _config_cache = _load_config()
    return _config_cache.copy()


def get_api_key():
    """返回 OPENAI_COMPATIBLE_API_KEY。"""
    return get_config().get("OPENAI_COMPATIBLE_API_KEY", "")


def get_base_url():
    """返回 OPENAI_COMPATIBLE_BASE_URL。"""
    return get_config().get("OPENAI_COMPATIBLE_BASE_URL", "")


def get_model():
    """返回 OPENAI_COMPATIBLE_MODEL。"""
    return get_config().get("OPENAI_COMPATIBLE_MODEL", "")


def get_openai_client_kwargs():
    """
    返回适合 openai 库的参数字典，可直接用于 OpenAI(base_url=..., api_key=...) 等。
    例如: OpenAI(**get_openai_client_kwargs())
    """
    return {
        "api_key": get_api_key(),
        "base_url": get_base_url(),
    }
# Generated By AI End (Cursor)
