# Generated By AI Start (Cursor)
"""
从 bib 文件中解析条目，提取可用于 Semantic Scholar 查询的标识（如 CorpusID）。
"""
import re
from pathlib import Path
from typing import List, Optional


def _extract_corpus_id_from_url(url: str) -> Optional[str]:
    if not url:
        return None
    m = re.search(r"CorpusID[:\s]*(\d+)", url, re.IGNORECASE)
    return m.group(1) if m else None


def _extract_arxiv_id_from_volume(volume: str) -> Optional[str]:
    if not volume:
        return None
    volume = volume.strip()
    if volume.lower().startswith("abs/"):
        return volume[4:].strip()
    m = re.match(r"(\d{4}\.\d{4,5})", volume)
    return m.group(1) if m else None


def _normalize_field(value: str) -> str:
    if not value:
        return ""
    return value.strip().strip("{},").strip()


def parse_bib_file(bib_path: str) -> List[dict]:
    """
    解析 bib 文件，返回条目列表。每条目至少包含：key, title, author, year, corpus_id（若有）。
    """
    path = Path(bib_path)
    if not path.exists():
        raise FileNotFoundError(f"Bib file not found: {bib_path}")
    text = path.read_text(encoding="utf-8", errors="replace")
    entries = []
    current = None
    key_match = None
    for line in text.splitlines():
        m = re.match(r"@\w+\s*\{\s*([^,]+)\s*,", line)
        if m:
            if current is not None:
                entries.append(_finish_entry(current, key_match))
            key_match = m.group(1).strip()
            current = {"key": key_match, "title": "", "author": "", "year": "", "url": "", "volume": ""}
            continue
        if current is None:
            continue
        for field in ("title", "author", "year", "url", "volume"):
            if re.match(r"\s*" + field + r"\s*[={]", line, re.IGNORECASE):
                raw = line.split("=", 1)[-1].strip().strip("{},").strip()
                current[field] = raw
                break
    if current is not None:
        entries.append(_finish_entry(current, key_match))
    return entries


def _finish_entry(current: dict, key_match: Optional[str]) -> dict:
    key = key_match or current.get("key", "")
    title = _normalize_field(current.get("title", ""))
    author = _normalize_field(current.get("author", ""))
    year = _normalize_field(current.get("year", ""))
    url = _normalize_field(current.get("url", ""))
    volume = _normalize_field(current.get("volume", ""))
    corpus_id = _extract_corpus_id_from_url(url)
    arxiv_id = _extract_arxiv_id_from_volume(volume)
    return {
        "key": key,
        "title": title,
        "author": author,
        "year": year,
        "url": url,
        "volume": volume,
        "corpus_id": corpus_id,
        "arxiv_id": arxiv_id,
    }
# Generated By AI End (Cursor)
