# Generated By AI Start (Cursor)
"""
从 Semantic Scholar 获取论文元数据并下载开放获取的 PDF。
"""
import re
import time
from pathlib import Path
from typing import Optional

import requests

try:
    from semanticscholar import SemanticScholar
except ImportError:
    SemanticScholar = None


def get_paper_by_corpus_id(corpus_id: str, api_key: Optional[str] = None) -> Optional[dict]:
    """
    使用 Corpus ID 从 Semantic Scholar 获取论文信息。
    返回包含 title, abstract, openAccessPdf 等字段的字典，失败返回 None。
    """
    if SemanticScholar is None:
        return _get_paper_via_http(corpus_id, api_key)
    try:
        sch = SemanticScholar(api_key=api_key) if api_key else SemanticScholar()
        paper = sch.get_paper(
            f"CorpusID:{corpus_id}",
            fields=["title", "authors", "year", "abstract", "openAccessPdf", "externalIds"],
        )
        if paper is None:
            return None
        if hasattr(paper, "raw_data"):
            return paper.raw_data
        return dict(paper) if hasattr(paper, "keys") else None
    except Exception:
        return _get_paper_via_http(corpus_id, api_key)


def _get_paper_via_http(corpus_id: str, api_key: Optional[str] = None) -> Optional[dict]:
    url = f"https://api.semanticscholar.org/graph/v1/paper/CorpusID:{corpus_id}"
    params = {"fields": "title,authors,year,abstract,openAccessPdf,externalIds"}
    headers = {}
    if api_key:
        headers["x-api-key"] = api_key
    try:
        r = requests.get(url, params=params, headers=headers or None, timeout=30)
        r.raise_for_status()
        return r.json()
    except Exception:
        return None


def get_pdf_url(paper: dict) -> Optional[str]:
    """从 API 返回的 paper 中取出开放获取 PDF 的 URL。"""
    oa = paper.get("openAccessPdf")
    if oa and isinstance(oa, dict):
        return oa.get("url")
    return None


def get_arxiv_id_from_paper(paper: dict) -> Optional[str]:
    """从 Semantic Scholar 返回的 paper 的 externalIds 中取出 arXiv ID。"""
    if not paper:
        return None
    ext = paper.get("externalIds")
    if isinstance(ext, dict):
        arxiv = ext.get("ArXiv") or ext.get("arxiv")
        if arxiv:
            return str(arxiv).strip()
    return None


ARXIV_PDF_BASE = "https://arxiv.org/pdf"


def download_pdf_from_arxiv(arxiv_id: str, save_path: Path) -> bool:
    """从 arXiv 下载 PDF 到 save_path，成功返回 True。"""
    aid = arxiv_id.strip()
    if aid.endswith(".pdf"):
        aid = aid[:-4]
    pdf_url = f"{ARXIV_PDF_BASE}/{aid}.pdf"
    return download_pdf(pdf_url, save_path)


def download_pdf(pdf_url: str, save_path: Path) -> bool:
    """将 PDF 下载到 save_path，成功返回 True。"""
    try:
        r = requests.get(pdf_url, timeout=60, stream=True)
        r.raise_for_status()
        save_path.parent.mkdir(parents=True, exist_ok=True)
        with open(save_path, "wb") as f:
            for chunk in r.iter_content(chunk_size=8192):
                f.write(chunk)
        return True
    except Exception:
        return False


def safe_filename(name: str, max_len: int = 120) -> str:
    """生成安全的文件名，避免非法字符。"""
    name = re.sub(r'[<>:"/\\|?*]', "_", name)
    name = name.strip(" .") or "paper"
    if len(name) > max_len:
        name = name[:max_len].rstrip()
    return name or "paper"


def fetch_and_download(
    corpus_id: str,
    output_dir: Path,
    title_fallback: str = "",
    api_key: Optional[str] = None,
    arxiv_id_from_bib: Optional[str] = None,
) -> dict:
    """
    根据 Corpus ID 获取论文信息并尝试下载 PDF。
    优先使用 Semantic Scholar 的 openAccessPdf；若无则用 arXiv ID（API 或 bib 中的 volume）从 arXiv 下载。
    返回 dict: paper, pdf_path, abstract, title, pdf_source（'semantic_scholar'|'arxiv'|None）。
    """
    result = {
        "paper": None,
        "pdf_path": None,
        "abstract": "",
        "title": title_fallback,
        "pdf_source": None,
    }
    paper = get_paper_by_corpus_id(corpus_id, api_key)
    if not paper:
        return result
    result["paper"] = paper
    result["title"] = paper.get("title") or title_fallback
    result["abstract"] = paper.get("abstract") or ""
    fname = safe_filename(result["title"]) + ".pdf"
    pdf_path = output_dir / fname

    pdf_url = get_pdf_url(paper)
    if pdf_url and download_pdf(pdf_url, pdf_path):
        result["pdf_path"] = pdf_path
        result["pdf_source"] = "semantic_scholar"
    else:
        arxiv_id = get_arxiv_id_from_paper(paper) or arxiv_id_from_bib
        if arxiv_id and download_pdf_from_arxiv(arxiv_id, pdf_path):
            result["pdf_path"] = pdf_path
            result["pdf_source"] = "arxiv"
    time.sleep(0.3)
    return result
# Generated By AI End (Cursor)
