# Generated By AI Start (Cursor)
"""
从已下载的 PDF 中提取正文文本，用于后续总结。
"""
from pathlib import Path
from typing import Optional

try:
    import fitz
except ImportError:
    fitz = None


def extract_text_from_pdf(pdf_path: Path, max_chars: int = 50000) -> Optional[str]:
    """
    使用 PyMuPDF 提取 PDF 正文。若未安装 PyMuPDF 或失败则返回 None。
    max_chars 用于截断过长文本，避免 API 超长。
    """
    if fitz is None or not pdf_path.exists():
        return None
    try:
        doc = fitz.open(pdf_path)
        parts = []
        total = 0
        for page in doc:
            text = page.get_text()
            if text:
                parts.append(text)
                total += len(text)
                if total >= max_chars:
                    break
        doc.close()
        return "\n".join(parts).strip() if parts else None
    except Exception:
        return None
# Generated By AI End (Cursor)
