# Generated By AI Start (Cursor)
"""
主入口：根据 bib 从 Semantic Scholar 下载论文并做四步总结，结果写入带时间戳的 Markdown。
"""
import argparse
import sys
from datetime import datetime
from pathlib import Path

_root = Path(__file__).resolve().parent
if str(_root) not in sys.path:
    sys.path.insert(0, str(_root))

from bib_parser import parse_bib_file
from paper_fetcher import fetch_and_download
from pdf_extract import extract_text_from_pdf
from summarizer import summarize_paper


def main():
    parser = argparse.ArgumentParser(description="从 bib 下载论文并生成四步总结")
    parser.add_argument(
        "--bib",
        default="citation.bib",
        help="Bib 文件路径，默认使用当前目录下的 citation.bib",
    )
    parser.add_argument(
        "--out-dir",
        default=None,
        help="论文与总结的输出根目录，不指定则使用当前目录下的 papers_YYYYMMDD_HHMMSS",
    )
    parser.add_argument(
        "--semantic-api-key",
        default=None,
        help="Semantic Scholar API Key（可选，用于提高限流）",
    )
    args = parser.parse_args()

    root = Path.cwd()
    bib_path = root / args.bib
    if not bib_path.exists():
        bib_path = Path(args.bib)
    if not bib_path.exists():
        print(f"错误：找不到 bib 文件 {args.bib}", file=sys.stderr)
        sys.exit(1)

    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    if args.out_dir:
        base_out = Path(args.out_dir)
    else:
        base_out = root / f"papers_{timestamp}"
    base_out.mkdir(parents=True, exist_ok=True)
    print(f"输出目录：{base_out.resolve()}")

    try:
        entries = parse_bib_file(str(bib_path))
    except Exception as e:
        print(f"解析 bib 失败：{e}", file=sys.stderr)
        sys.exit(2)

    if not entries:
        print("bib 中无有效条目。")
        return

    md_name = f"summaries_{timestamp}.md"
    md_path = base_out / md_name
    with open(md_path, "w", encoding="utf-8") as mdf:
        mdf.write(f"# 论文总结\n\n生成时间：{datetime.now().isoformat()}\n\n")
        mdf.write(f"Bib 文件：{bib_path}\n\n---\n\n")

    done = 0
    for i, entry in enumerate(entries):
        key = entry.get("key", "")
        title_bib = entry.get("title", "")
        corpus_id = entry.get("corpus_id")
        if not corpus_id:
            print(f"[{i+1}/{len(entries)}] 跳过（无 CorpusID）：{key} - {title_bib[:50]}...")
            with open(md_path, "a", encoding="utf-8") as mdf:
                mdf.write(f"## [{key}] {title_bib}\n\n")
                mdf.write("（未提供 Semantic Scholar CorpusID，无法获取与总结。）\n\n---\n\n")
            continue

        print(f"[{i+1}/{len(entries)}] 获取：{key} - {title_bib[:50]}...")
        result = fetch_and_download(
            corpus_id=corpus_id,
            output_dir=base_out,
            title_fallback=title_bib,
            api_key=args.semantic_api_key,
            arxiv_id_from_bib=entry.get("arxiv_id"),
        )
        title = result.get("title") or title_bib
        abstract = result.get("abstract") or ""
        pdf_path = result.get("pdf_path")
        pdf_source = result.get("pdf_source")
        if pdf_path:
            print(f"        已下载 PDF（来源：{pdf_source or 'unknown'}） -> {pdf_path.name}")
        else:
            print(f"        未获取到 PDF，将使用摘要进行总结")

        content = abstract
        if pdf_path:
            pdf_text = extract_text_from_pdf(pdf_path)
            if pdf_text:
                content = pdf_text
        if not content.strip():
            content = f"标题：{title}\n（无摘要与 PDF 正文）"

        print(f"        总结中...")
        summary = summarize_paper(title=title, content=content)

        with open(md_path, "a", encoding="utf-8") as mdf:
            mdf.write(f"## [{key}] {title}\n\n")
            mdf.write(summary)
            mdf.write("\n\n---\n\n")
        done += 1

    print(f"完成。共处理 {done}/{len(entries)} 篇，总结已写入：{md_path.resolve()}")
# Generated By AI End (Cursor)


if __name__ == "__main__":
    main()
