# Generated By AI Start (Cursor)
"""
使用配置的 OpenAI 兼容 API 对论文内容进行四步总结。
"""
from typing import Optional

try:
    from openai import OpenAI
except ImportError:
    OpenAI = None


SUMMARY_PROMPT_TEMPLATE = """请根据以下论文信息，按下面四个维度用中文总结，每个维度一段，不要遗漏。

【论文标题】{title}

【摘要或正文片段】
{content}

---
请严格按以下格式输出（保留标题行）：

**一句话总结：** 
（这篇论文到底做了一件什么事？）

**研究背景：** 
（在这个领域，大家之前遇到了什么痛点或难题？）

**核心创新：** 
（作者提出了什么新方法来解决这个难题？）

**主要结论：** 
（实验/研究证明了什么？效果如何？）
"""


def summarize_paper(
    title: str,
    content: str,
    api_key: Optional[str] = None,
    base_url: Optional[str] = None,
    model: Optional[str] = None,
) -> str:
    """
    调用 LLM 对论文进行四步总结。content 可为摘要或 PDF 正文片段。
    若未配置 API 或调用失败，返回占位说明。
    """
    if not content or not content.strip():
        content = "（无摘要或正文内容，仅根据标题推测。）"
    if len(content) > 28000:
        content = content[:28000] + "\n\n...（已截断）"
    prompt = SUMMARY_PROMPT_TEMPLATE.format(title=title or "未知标题", content=content.strip())

    if OpenAI is None:
        return "（未安装 openai 库，无法调用总结 API。）"

    try:
        from api_config_loader import get_api_key, get_base_url, get_model
        key = api_key or get_api_key()
        url = base_url or get_base_url()
        mod = model or get_model()
        if not key or not url or not mod:
            return "（未配置 OPENAI_COMPATIBLE_API_KEY / BASE_URL / MODEL，请检查 api_config.env。）"
        client = OpenAI(api_key=key, base_url=url)
        resp = client.chat.completions.create(
            model=mod,
            messages=[{"role": "user", "content": prompt}],
            temperature=0.3,
        )
        text = (resp.choices[0].message.content or "").strip()
        return text if text else "（API 返回为空。）"
    except Exception as e:
        return f"（总结 API 调用失败：{e}）"
# Generated By AI End (Cursor)
